### ISSUE TITLE
Add |sudo: false| to .travis.yml

### ISSUE THREAD

**Issue by edmorley** [ionelmc/cookiecutter-pylibrary-minimal#4]
To match:
https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/.travis.yml#L3

Travis have a newer container based stack that runs on EC2, that is both faster & allows the use of extra features (such as dependency caching):
http://docs.travis-ci.com/user/workers/container-based-infrastructure/

To use it, |sudo: false| must be set.

**Comment by ionelmc** [comment]
Thanks for report.

**Comment by edmorley** [comment]
No problem :-)

**Comment by ionelmc** [comment]
Also, worth noting that you can just use https://github.com/ionelmc/cookiecutter-pylibrary - it has an option to disable the matrix boostrap thing. It will work just like `cookiecutter-pylibrary` but with pytest as the test runner.
